ExternalProject_Add(curl
  DEPENDS brotli
          libpsl
          zlib
          zstd
  URL https://github.com/curl/curl/releases/download/curl-8_18_0/curl-8.18.0.tar.bz2
  URL_HASH MD5=7dc4bafd82087e22c25fd5d5f6f97beb
  DOWNLOAD_EXTRACT_TIMESTAMP 1
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DBUILD_CURL_EXE=OFF
    -DBUILD_EXAMPLES=OFF
    -DBUILD_LIBCURL_DOCS=OFF
    -DBUILD_MISC_DOCS=OFF
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_STATIC_CURL=OFF
    -DBUILD_STATIC_LIBS=ON
    -DBUILD_TESTING=OFF
    -DCURL_BROTLI=ON
    -DCURL_CA_SEARCH_SAFE=OFF
    -DCURL_CLANG_TIDY=OFF
    -DCURL_COMPLETION_FISH=OFF
    -DCURL_COMPLETION_ZSH=OFF
    -DCURL_DISABLE_CA_SEARCH=OFF
    -DCURL_DISABLE_INSTALL=OFF
    -DCURL_DISABLE_OPENSSL_AUTO_LOAD=OFF
    -DCURL_ENABLE_SSL=ON
    -DCURL_LTO=OFF
    -DCURL_STATIC_CRT=ON
    -DCURL_TARGET_WINDOWS_VERSION=0x0A00
    -DCURL_USE_GNUTLS=OFF
    -DCURL_USE_LIBUV=OFF
    -DCURL_USE_MBEDTLS=OFF
    -DCURL_USE_OPENSSL=OFF
    -DCURL_USE_PKGCONFIG=ON
    -DCURL_USE_RUSTLS=OFF
    -DCURL_USE_SCHANNEL=ON
    -DCURL_USE_WOLFSSL=OFF
    -DCURL_WERROR=OFF
    -DCURL_WINDOWS_SSPI=OFF
    -DCURL_ZLIB=ON
    -DCURL_ZSTD=ON
    -DENABLE_ARES=OFF
    -DENABLE_CURLDEBUG=OFF
    -DENABLE_CURL_MANUAL=OFF
    -DENABLE_DEBUG=OFF
    -DENABLE_THREADED_RESOLVER=ON
    -DENABLE_UNICODE=OFF
    -DENABLE_UNIX_SOCKETS=ON
    -DLIBCURL_OUTPUT_NAME=libcurl
    -DPICKY_COMPILER=ON
    -DUSE_ECH=OFF
    -DUSE_HTTPSRR=OFF
    -DUSE_LIBIDN2=0FF
    -DUSE_LIBRTMP=OFF
    -DUSE_MSH3=OFF
    -DUSE_NGHTTP2=OFF
    -DUSE_NGTCP2=OFF
    -DUSE_OPENSSL_QUIC=OFF
    -DUSE_QUICHE=OFF
    -DUSE_SSLS_EXPORT=OFF
    -DUSE_WIN32_IDN=OFF
    -DUSE_WIN32_LDAP=ON
    -D_CURL_PREFILL=ON
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

