ExternalProject_Add(
  expat
  URL https://github.com/libexpat/libexpat/releases/download/R_2_6_3/expat-2.6.3.tar.bz2
  URL_HASH MD5=c70040a3f2743d9645cb029d3c9a7c89
  DOWNLOAD_EXTRACT_TIMESTAMP 1
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DEXPAT_BUILD_DOCS=OFF
    -DEXPAT_BUILD_EXAMPLES=OFF
    -DEXPAT_BUILD_FUZZERS=OFF
    -DEXPAT_BUILD_PKGCONFIG=ON
    -DEXPAT_BUILD_TESTS=OFF
    -DEXPAT_BUILD_TOOLS=OFF
    -DEXPAT_CHAR_TYPE=char
    -DEXPAT_ENABLE_INSTALL=ON
    -DEXPAT_OSSFUZZ_BUILD=OFF
    -DEXPAT_SHARED_LIBS=OFF
    -DEXPAT_WARNINGS_AS_ERRORS=OFF
    -DEXPAT_WITH_GETRANDOM=AUTO
    -DEXPAT_WITH_LIBBSD=OFF
    -DEXPAT_WITH_SYS_GETRANDOM=AUTO
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

