ExternalProject_Add(
  highway
  URL https://github.com/google/highway/releases/download/1.4.0/highway-1.4.0.tar.gz
  URL_HASH SHA256=36f672ab48ddb3c8555e9e89e16fe400cd7d16c6eb455a1a3d0c146a63ababdc
  DOWNLOAD_EXTRACT_TIMESTAMP 1
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DBUILD_GMOCK=OFF
    -DBUILD_TESTING=OFF
    -DHWY_CMAKE_ARM7=OFF
    -DHWY_CMAKE_HEADER_ONLY=OFF
    -DHWY_CMAKE_RVV=OFF
    -DHWY_CMAKE_SSE2=ON
    -DHWY_ENABLE_CONTRIB=ON
    -DHWY_ENABLE_EXAMPLES=OFF
    -DHWY_ENABLE_INSTALL=ON
    -DHWY_ENABLE_TESTS=OFF
    -DHWY_SYSTEM_GTEST=OFF
    -DHWY_WARNINGS_ARE_ERRORS=OFF
    -DINSTALL_GTEST=OFF
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

