ExternalProject_Add(
  highway
  URL https://github.com/google/highway/archive/da7098aef8585b9aac53f07bd536366a5eccb9ff.tar.gz
  URL_HASH MD5=dbd44d9c58a96bf39ccb6a73ede4f669
  DOWNLOAD_EXTRACT_TIMESTAMP 1
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DBUILD_GMOCK=OFF
    -DBUILD_TESTING=OFF
    -DHWY_CMAKE_ARM7=OFF
    -DHWY_CMAKE_HEADER_ONLY=OFF
    -DHWY_CMAKE_RVV=OFF
    -DHWY_CMAKE_SSE2=ON
    -DHWY_ENABLE_CONTRIB=ON
    -DHWY_ENABLE_EXAMPLES=OFF
    -DHWY_ENABLE_INSTALL=ON
    -DHWY_ENABLE_TESTS=OFF
    -DHWY_SYSTEM_GTEST=OFF
    -DHWY_WARNINGS_ARE_ERRORS=OFF
    -DINSTALL_GTEST=OFF
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

