ExternalProject_Add(
  libsdl3
  URL https://github.com/libsdl-org/SDL/archive/refs/tags/release-3.2.28.tar.gz
  URL_HASH MD5=23900c41241d348fa2d0757521e141bb
  DOWNLOAD_EXTRACT_TIMESTAMP 1
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DSDL_ALSA=OFF
    -DSDL_ASAN=OFF
    -DSDL_ASSEMBLY=ON
    -DSDL_ASSERTIONS=auto
    -DSDL_AUDIO=ON
    -DSDL_AVX=ON
    -DSDL_AVX2=ON
    -DSDL_AVX512F=ON
    -DSDL_BACKGROUNDING_SIGNAL=OFF
    -DSDL_CAMERA=ON
    -DSDL_CCACHE=ON
    -DSDL_CLANG_TIDY=OFF
    -DSDL_CLOCK_GETTIME=OFF
    -DSDL_DEPS_SHARED=OFF
    -DSDL_DIALOG=ON
    -DSDL_DIRECTX=ON
    -DSDL_DISKAUDIO=ON
    -DSDL_DUMMYAUDIO=ON
    -DSDL_DUMMYCAMERA=ON
    -DSDL_DUMMYVIDEO=ON
    -DSDL_EXAMPLES=OFF
    -DSDL_FOREGROUNDING_SIGNAL=OFF
    -DSDL_GCC_ATOMICS=ON
    -DSDL_GPU_DXVK=OFF
    -DSDL_GPU=ON
    -DSDL_HAPTIC=ON
    -DSDL_HIDAPI_JOYSTICK=ON
    -DSDL_HIDAPI_LIBUSB=ON
    -DSDL_HIDAPI=ON
    -DSDL_INSTALL_CPACK=ON
    -DSDL_INSTALL_DOCS=OFF
    -DSDL_INSTALL_TESTS=OFF
    -DSDL_INSTALL=ON
    -DSDL_JACK=OFF
    -DSDL_JOYSTICK=ON
    -DSDL_KMSDRM=OFF
    -DSDL_LIBC=ON
    -DSDL_LIBICONV=ON
    -DSDL_LIBUDEV=ON
    -DSDL_MMX=ON
    -DSDL_OFFSCREEN=ON
    -DSDL_OPENGL=ON
    -DSDL_OPENGLES=ON
    -DSDL_OPENVR=OFF
    -DSDL_PIPEWIRE=OFF
    -DSDL_POWER=ON
    -DSDL_PTHREADS=OFF
    -DSDL_PULSEAUDIO=OFF
    -DSDL_RELOCATABLE=OFF
    -DSDL_RENDER_D3D=ON
    -DSDL_RENDER_D3D11=ON
    -DSDL_RENDER_D3D12=ON
    -DSDL_RENDER_GPU=ON
    -DSDL_RENDER_METAL=OFF
    -DSDL_RENDER_VULKAN=ON
    -DSDL_RENDER=ON
    -DSDL_RPATH=OFF
    -DSDL_SENSOR=ON
    -DSDL_SHARED=OFF
    -DSDL_SNDIO=OFF
    -DSDL_SSE=ON
    -DSDL_SSE2=ON
    -DSDL_SSE3=ON
    -DSDL_SSE4_1=ON
    -DSDL_SSE4_2=ON
    -DSDL_STATIC=ON
    -DSDL_SYSTEM_ICONV=OFF
    -DSDL_TEST_LIBRARY=OFF
    -DSDL_TESTS_TIMEOUT_MULTIPLIER=1
    -DSDL_UNINSTALL=OFF
    -DSDL_VIDEO=ON
    -DSDL_VIRTUAL_JOYSTICK=ON
    -DSDL_VULKAN=ON
    -DSDL_WASAPI=ON
    -DSDL_WAYLAND=OFF
    -DSDL_WERROR=OFF
    -DSDL_X11=OFF
    -DSDL_XINPUT=ON
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA} install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)
