ExternalProject_Add(
  libxml2
  DEPENDS libiconv
          zlib
  URL https://github.com/GNOME/libxml2/archive/refs/tags/v2.15.3.tar.gz
  URL_HASH SHA256=5c6060277173270356c3f1c321a640ab629bdabc5e5ba9095b99e00759ba0c39
  DOWNLOAD_EXTRACT_TIMESTAMP 1
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DBUILD_SHARED_LIBS=OFF
    -DLIBXML2_WITH_C14N=ON
    -DLIBXML2_WITH_CATALOG=ON
    -DLIBXML2_WITH_DEBUG=OFF
    -DLIBXML2_WITH_DOCS=OFF
    -DLIBXML2_WITH_HTML=ON
    -DLIBXML2_WITH_HTTP=ON
    -DLIBXML2_WITH_ICONV=ON
    -DLIBXML2_WITH_ICU=OFF
    -DLIBXML2_WITH_ISO8859X=OFF
    -DLIBXML2_WITH_LEGACY=ON
    -DLIBXML2_WITH_MODULES=ON
    -DLIBXML2_WITH_OUTPUT=ON
    -DLIBXML2_WITH_PATTERN=ON
    -DLIBXML2_WITH_PROGRAMS=OFF
    -DLIBXML2_WITH_PUSH=ON
    -DLIBXML2_WITH_PYTHON=OFF
    -DLIBXML2_WITH_READER=ON
    -DLIBXML2_WITH_READLINE=OFF
    -DLIBXML2_WITH_REGEXPS=ON
    -DLIBXML2_WITH_RELAXNG=ON
    -DLIBXML2_WITH_SAX1=ON
    -DLIBXML2_WITH_SCHEMAS=ON
    -DLIBXML2_WITH_SCHEMATRON=OFF
    -DLIBXML2_WITH_TESTS=OFF
    -DLIBXML2_WITH_THREAD_ALLOC=OFF
    -DLIBXML2_WITH_THREADS=ON
    -DLIBXML2_WITH_TLS=ON
    -DLIBXML2_WITH_VALID=ON
    -DLIBXML2_WITH_WRITER=ON
    -DLIBXML2_WITH_XINCLUDE=ON
    -DLIBXML2_WITH_XPATH=ON
    -DLIBXML2_WITH_XPTR=ON
BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)
