ExternalProject_Add(
  libxml2
  DEPENDS libiconv
  GIT_REPOSITORY https://github.com/GNOME/libxml2.git
  GIT_SHALLOW 1
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR> -G Ninja
    -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_SHARED_LIBS=OFF
    -DLIBXML2_WITH_C14N=ON
    -DLIBXML2_WITH_CATALOG=ON
    -DLIBXML2_WITH_DEBUG=OFF
    -DLIBXML2_WITH_FTP=OFF
    -DLIBXML2_WITH_HTML=ON
    -DLIBXML2_WITH_HTTP=ON
    -DLIBXML2_WITH_ICONV=ON
    -DLIBXML2_WITH_ICU=OFF
    -DLIBXML2_WITH_ISO8859X=ON
    -DLIBXML2_WITH_LEGACY=OFF
    -DLIBXML2_WITH_LZMA=OFF
    -DLIBXML2_WITH_MEM_DEBUG=OFF
    -DLIBXML2_WITH_MODULES=ON
    -DLIBXML2_WITH_OUTPUT=ON
    -DLIBXML2_WITH_PATTERN=ON
    -DLIBXML2_WITH_PROGRAMS=OFF
    -DLIBXML2_WITH_PUSH=ON
    -DLIBXML2_WITH_PYTHON=OFF
    -DLIBXML2_WITH_READER=ON
    -DLIBXML2_WITH_REGEXPS=ON
    -DLIBXML2_WITH_SAX1=ON
    -DLIBXML2_WITH_SCHEMAS=ON
    -DLIBXML2_WITH_SCHEMATRON=ON
    -DLIBXML2_WITH_TESTS=OFF
    -DLIBXML2_WITH_THREADS=ON
    -DLIBXML2_WITH_THREAD_ALLOC=OFF
    -DLIBXML2_WITH_TREE=ON
    -DLIBXML2_WITH_VALID=ON
    -DLIBXML2_WITH_WRITER=ON
    -DLIBXML2_WITH_XINCLUDE=ON
    -DLIBXML2_WITH_XPATH=ON
    -DLIBXML2_WITH_XPTR=ON
    -DLIBXML2_WITH_XPTR_LOCS=OFF
    -DLIBXML2_WITH_ZLIB=ON
BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

force_rebuild_git(libxml2)
