ExternalProject_Add(
  minizip
  DEPENDS bzip2
          zlib
          zstd
  GIT_REPOSITORY https://github.com/zlib-ng/minizip-ng.git
  GIT_REMOTE_NAME origin
  GIT_TAG develop
  GIT_SHALLOW 1
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DMZ_BUILD_FUZZ_TESTS=OFF
    -DMZ_BUILD_TESTS=OFF
    -DMZ_BUILD_UNIT_TESTS=OFF
    -DMZ_BZIP2=ON
    -DMZ_CODE_COVERAGE=OFF
    -DMZ_COMPAT=ON
    -DMZ_COMPRESS_ONLY=OFF
    -DMZ_DECOMPRESS_ONLY=OFF
    -DMZ_FETCH_LIBS=OFF
    -DMZ_FORCE_FETCH_LIBS=OFF
    -DMZ_ICONV=ON
    -DMZ_LIBBSD=OFF
    -DMZ_LIBCOMP=OFF
    -DMZ_LZMA=OFF
    -DMZ_OPENSSL=OFF
    -DMZ_PKCRYPT=ON
    -DMZ_SIGNING=ON
    -DMZ_WZAES=ON
    -DMZ_ZLIB=ON
    -DMZ_ZSTD=ON
  BUILD_COMMAND ${NINJA}
  INSTALL_COMMAND ${NINJA} install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

force_rebuild_git(minizip)
