  ExternalProject_Add(
  shaderc
  GIT_REPOSITORY https://github.com/rorgoroth/mpv-shaderc.git
  GIT_SHALLOW 1
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DALLOW_EXTERNAL_SPIRV_TOOLS=OFF
    -DBUILD_EXTERNAL=ON
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_WERROR=OFF
    -DDISABLE_EXCEPTIONS=OFF
    -DDISABLE_RTTI=ON
    -DENABLE_EXCEPTIONS=OFF
    -DENABLE_EXCEPTIONS_ON_MSVC=OFF
    -DENABLE_GLSLANG_BINARIES=OFF
    -DENABLE_GLSLANG_JS=OFF
    -DENABLE_HLSL=ON
    -DENABLE_OPT=OFF
    -DENABLE_RTTI=OFF
    -DENABLE_SPVREMAPPER=ON
    -DGLSLANG_TESTS=OFF
    -DSHADERC_ENABLE_WERROR_COMPILE=ON
    -DSHADERC_ENABLE_WGSL_OUTPUT=OFF
    -DSHADERC_SKIP_COPYRIGHT_CHECK=ON
    -DSHADERC_SKIP_EXAMPLES=ON
    -DSHADERC_SKIP_INSTALL=ON
    -DSHADERC_SKIP_TESTS=ON
    -DSPIRV_ALLOW_TIMERS=ON
    -DSPIRV_BUILD_COMPRESSION=OFF
    -DSPIRV_BUILD_FUZZER=OFF
    -DSPIRV_BUILD_LIBFUZZER_TARGETS=OFF
    -DSPIRV_CHECK_CONTEXT=ON
    -DSPIRV_COLOR_TERMINAL=ON
    -DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS=OFF
    -DSPIRV_HEADERS_ENABLE_INSTALL=OFF
    -DSPIRV_HEADERS_ENABLE_TESTS=OFF
    -DSPIRV_LOG_DEBUG=OFF
    -DSPIRV_SKIP_EXECUTABLES=ON
    -DSPIRV_SKIP_TESTS=ON
    -DSPIRV_TOOLS_BUILD_STATIC=ON
    -DSPIRV_TOOLS_INSTALL_EMACS_HELP=OFF
    -DSPIRV_WARN_EVERYTHING=OFF
    -DSPIRV_WERROR=ON
    -Dgtest_force_shared_crt=ON
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ""
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

ExternalProject_Add_Step(
  shaderc manual-install
  DEPENDEES build
  COMMAND
    ${CMAKE_COMMAND} -E copy_directory
    <SOURCE_DIR>/libshaderc/include/shaderc
    ${MINGW_INSTALL_PREFIX}/include/shaderc
  COMMAND
    ${CMAKE_COMMAND} -E copy
    <BINARY_DIR>/libshaderc/libshaderc_combined.a
    ${MINGW_INSTALL_PREFIX}/lib/libshaderc_combined.a
  COMMAND
    ${CMAKE_COMMAND} -E copy
    <BINARY_DIR>/shaderc_combined.pc
    ${MINGW_INSTALL_PREFIX}/lib/pkgconfig/shaderc.pc
  COMMAND
    ${CMAKE_COMMAND} -E copy
    <BINARY_DIR>/shaderc_combined.pc
    ${MINGW_INSTALL_PREFIX}/lib/pkgconfig/shaderc_combined.pc
  COMMENT "Manually installing")

force_rebuild_git(shaderc)
