ExternalProject_Add(
  svtav1
  GIT_REPOSITORY https://gitlab.com/AOMediaCodec/SVT-AV1.git
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC-NLTO} cmake -H<SOURCE_DIR> -B<BINARY_DIR> -G Ninja
    -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_APPS=OFF
    -DBUILD_DEC=OFF
    -DBUILD_ENC=ON
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_TESTING=OFF
    -DENABLE_AVX512=OFF
    -DENABLE_NASM=ON
    -DSVT_AV1_LTO=OFF
  BUILD_COMMAND ${NINJA-NLTO} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA-NLTO} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

force_rebuild_git(svtav1)
