ExternalProject_Add(
  svtav1
  GIT_REPOSITORY https://gitlab.com/AOMediaCodec/SVT-AV1.git
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC-NLTO} cmake -H<SOURCE_DIR> -B<BINARY_DIR>
    ${cmake_conf_args}
    -DBUILD_APPS=OFF
    -DBUILD_DEC=OFF
    -DBUILD_ENC=ON

    -DENABLE_AVX512=OFF
    -DENABLE_NASM=ON
    -DSVT_AV1_LTO=OFF
  BUILD_COMMAND ${NINJA-NLTO} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA-NLTO} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

force_rebuild_git(svtav1)
