ExternalProject_Add(uchardet
    GIT_REPOSITORY git://anongit.freedesktop.org/uchardet/uchardet
    GIT_SHALLOW 1
    UPDATE_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX}
        -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
        -DTARGET_ARCHITECTURE=${TARGET_CPU_FAMILY}
        -DBUILD_BINARY=OFF
        -DBUILD_SHARED_LIBS=OFF
        -DBUILD_STATIC=ON
        -DCMAKE_BUILD_TYPE=Release
    BUILD_COMMAND ${CMAKE_MAKE_PROGRAM}
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install
    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)

force_rebuild_git(uchardet)
extra_step(uchardet)
