ExternalProject_Add(
  uchardet
  URL https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.8.tar.xz
  URL_HASH MD5=9e267be7aee81417e5875086dd9d44fd
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR> -B<BINARY_DIR> -G Ninja
    -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
    -DTARGET_ARCHITECTURE=x86_64
    -DBUILD_BINARY=OFF
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_STATIC=ON
    -DCMAKE_BUILD_TYPE=Release
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

#force_rebuild_git(uchardet)
