if(${TARGET_CPU} MATCHES "x86_64")
    set(high_bit_depth "-DHIGH_BIT_DEPTH=ON -DENABLE_HDR10_PLUS=ON")
else()
    set(high_bit_depth "-DHIGH_BIT_DEPTH=OFF")
endif()

ExternalProject_Add(
  x265
  GIT_REPOSITORY https://bitbucket.org/multicoreware/x265_git.git
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND
    ${EXEC} cmake -H<SOURCE_DIR>/source -B<BINARY_DIR> -G Ninja
    -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
    -DCMAKE_BUILD_TYPE=Release
    -DCHECKED_BUILD=OFF
    -DDETAILED_CU_STATS=OFF
    -DENABLE_AGGRESSIVE_CHECKS=OFF
    -DENABLE_ASSEMBLY=ON
    -DENABLE_CLI=OFF
    -DENABLE_PIC=OFF
    -DENABLE_PPA=OFF
    -DENABLE_SHARED=OFF
    -DENABLE_SVT_HEVC=OFF
    -DENABLE_TESTS=OFF
    -DENABLE_VTUNE=OFF
    -DMAIN12=OFF
    -DSTATIC_LINK_CRT=ON
    -DWARNINGS_AS_ERRORS=OFF
    -DWINXP_SUPPORT=OFF
    ${high_bit_depth}
  BUILD_COMMAND ${NINJA} -C <BINARY_DIR>
  INSTALL_COMMAND ${NINJA} -C <BINARY_DIR> install
  LOG_DOWNLOAD 1
  LOG_UPDATE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1)

force_rebuild_git(x265)
clean_build(x265 install)
